In [16]:
import numpy as np
import tensorflow as tf
from tensorflow import keras
from sklearn.model_selection import train_test_split
from tensorflow.keras import layers
import pandas as pd

In [17]:
df = pd.DataFrame({
    "soil_moisture": [0.10, 0.15, 0.20, 0.25, 0.40, 0.60, 0.35, 0.18,
                      0.45, 0.05, 0.80, 0.27, 0.55, 0.70, 0.12, 0.30],
    "temperature_c": [34, 30, 26, 22, 28, 30, 19, 22,
                      35, 24, 33, 33, 21, 25, 20, 29],
    "sunlight_hours": [9, 8, 7, 4, 8, 10, 3, 10,
                       12, 5, 9, 11, 2, 6, 1, 9],
    "needs_water": [1, 1, 1, 0, 0, 0, 0, 1,
                    0, 1, 0, 1, 0, 0, 1, 1]
})
df

    soil_moisture  temperature_c  sunlight_hours  needs_water
0            0.10             34               9            1
1            0.15             30               8            1
2            0.20             26               7            1
3            0.25             22               4            0
4            0.40             28               8            0
5            0.60             30              10            0
6            0.35             19               3            0
7            0.18             22              10            1
8            0.45             35              12            0
9            0.05             24               5            1
10           0.80             33               9            0
11           0.27             33              11            1
12           0.55             21               2            0
13           0.70             25               6            0
14           0.12             20               1            1
15           0.30             29               9            1

In [18]:
df.columns

Index(['soil_moisture', 'temperature_c', 'sunlight_hours', 'needs_water'], dtype='object')

In [20]:
X = df[['soil_moisture', 'temperature_c', 'sunlight_hours']]
y = df['needs_water']

In [21]:
# Normalizing(Min-max scaling) the input features since deep learning works better on normalized vlaue
X_min = X.min()
X_max = X.max()
X_scaled = (X - X_min) / (X_max - X_min)

In [22]:
X_scaled

    soil_moisture  temperature_c  sunlight_hours
0        0.066667         0.9375        0.727273
1        0.133333         0.6875        0.636364
2        0.200000         0.4375        0.545455
3        0.266667         0.1875        0.272727
4        0.466667         0.5625        0.636364
5        0.733333         0.6875        0.818182
6        0.400000         0.0000        0.181818
7        0.173333         0.1875        0.818182
8        0.533333         1.0000        1.000000
9        0.000000         0.3125        0.363636
10       1.000000         0.8750        0.727273
11       0.293333         0.8750        0.909091
12       0.666667         0.1250        0.090909
13       0.866667         0.3750        0.454545
14       0.093333         0.0625        0.000000
15       0.333333         0.6250        0.727273

## Spliting training and testing data

In [23]:
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size = 0.25, random_state = 42, stratify = y)

## Creating Model

In [27]:
model = keras.Sequential([
    # input layer
    layers.Input(shape= (X_train.shape[1],)),
    # X_train.shape[1] will tell the no of columns i.e, no. of features, in X_train matrix
    # shape will tell the no of neurons in the input layer

    # Hidden Layer
    layers.Dense(8, activation = 'relu'),
    # 8 = no of neurons in the hidden layer

    # Output layer
    layers.Dense(1, activation = 'sigmoid')
])

## Telling the model about which optimizer, loss function, and metrics to use

In [32]:
model.compile(optimizer = 'sgd', loss = 'binary_crossentropy', metrics = ['accuracy'])

## Training the model

In [34]:
history = model.fit(
    X_train.values, y_train.values,
    validation_data = (X_test.values, y_test.values),
    epochs = 100, batch_size = 4, verbose = 1
)

Epoch 1/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.5833 - loss: 0.6579 - val_accuracy: 0.5000 - val_loss: 0.6501
Epoch 2/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.5833 - loss: 0.6563 - val_accuracy: 0.5000 - val_loss: 0.6498
Epoch 3/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 0.6667 - loss: 0.6559 - val_accuracy: 0.5000 - val_loss: 0.6495
Epoch 4/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.6667 - loss: 0.6551 - val_accuracy: 0.5000 - val_loss: 0.6492
Epoch 5/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.6667 - loss: 0.6542 - val_accuracy: 0.5000 - val_loss: 0.6489
Epoch 6/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.6667 - loss: 0.6537 - val_accuracy: 0.5000 - val_loss: 0.6485
Epoch 7/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.6667 - loss: 0.6556 - val_accuracy: 0.5000 - val_loss: 0.6482
Epoch 8/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 0.6667 - loss: 0.6533 - val_accuracy: 0.5000 - val_loss: 0.6479
Epoch 9/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.6667 - loss: 0.6529 - val_accuracy: 0.5000 - val_loss: 0.6475
Epoch 10/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.6667 - loss: 0.6519 - val_accuracy: 0.5000 - val_loss: 0.6472
Epoch 11/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 0.6667 - loss: 0.6521 - val_accuracy: 0.5000 - val_loss: 0.6469
Epoch 12/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.6667 - loss: 0.6515 - val_accuracy: 0.5000 - val_loss: 0.6465
Epoch 13/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 0.6667 - loss: 0.6515 - val_accuracy: 0.5000 - val_loss: 0.6462
Epoch 14/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.6667 - loss: 0.6500 - val_accuracy: 0.5000 - val_loss: 0.6459
Epoch 15/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 0.6667 - loss: 0.6515 - val_accuracy: 0.5000 - val_loss: 0.6455
Epoch 16/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.6667 - loss: 0.6497 - val_accuracy: 0.5000 - val_loss: 0.6452
Epoch 17/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 0.6667 - loss: 0.6495 - val_accuracy: 0.5000 - val_loss: 0.6449
Epoch 18/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 0.6667 - loss: 0.6482 - val_accuracy: 0.5000 - val_loss: 0.6445
Epoch 19/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.6667 - loss: 0.6477 - val_accuracy: 0.5000 - val_loss: 0.6442
Epoch 20/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 0.6667 - loss: 0.6479 - val_accuracy: 0.5000 - val_loss: 0.6439
Epoch 21/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 0.6667 - loss: 0.6468 - val_accuracy: 0.5000 - val_loss: 0.6435
Epoch 22/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 0.6667 - loss: 0.6462 - val_accuracy: 0.5000 - val_loss: 0.6431
Epoch 23/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.6667 - loss: 0.6463 - val_accuracy: 0.7500 - val_loss: 0.6428
Epoch 24/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 0.6667 - loss: 0.6458 - val_accuracy: 0.7500 - val_loss: 0.6424
Epoch 25/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 0.6667 - loss: 0.6456 - val_accuracy: 0.7500 - val_loss: 0.6420
Epoch 26/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 0.6667 - loss: 0.6444 - val_accuracy: 0.7500 - val_loss: 0.6417
Epoch 27/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 0.6667 - loss: 0.6440 - val_accuracy: 0.7500 - val_loss: 0.6413
Epoch 28/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 0.6667 - loss: 0.6441 - val_accuracy: 0.7500 - val_loss: 0.6410
Epoch 29/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.6667 - loss: 0.6429 - val_accuracy: 0.7500 - val_loss: 0.6406
Epoch 30/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.6667 - loss: 0.6425 - val_accuracy: 0.7500 - val_loss: 0.6403
Epoch 31/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.6667 - loss: 0.6420 - val_accuracy: 0.7500 - val_loss: 0.6399
Epoch 32/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 0.6667 - loss: 0.6424 - val_accuracy: 0.7500 - val_loss: 0.6396
Epoch 33/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 0.6667 - loss: 0.6444 - val_accuracy: 0.7500 - val_loss: 0.6392
Epoch 34/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 0.6667 - loss: 0.6427 - val_accuracy: 0.7500 - val_loss: 0.6388
Epoch 35/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 0.6667 - loss: 0.6407 - val_accuracy: 0.7500 - val_loss: 0.6385
Epoch 36/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.6667 - loss: 0.6423 - val_accuracy: 0.7500 - val_loss: 0.6381
Epoch 37/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.6667 - loss: 0.6402 - val_accuracy: 0.7500 - val_loss: 0.6377
Epoch 38/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.6667 - loss: 0.6407 - val_accuracy: 0.7500 - val_loss: 0.6373
Epoch 39/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 0.6667 - loss: 0.6389 - val_accuracy: 0.7500 - val_loss: 0.6369
Epoch 40/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.6667 - loss: 0.6387 - val_accuracy: 0.7500 - val_loss: 0.6366
Epoch 41/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.6667 - loss: 0.6380 - val_accuracy: 0.7500 - val_loss: 0.6362
Epoch 42/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 0.6667 - loss: 0.6371 - val_accuracy: 0.7500 - val_loss: 0.6359
Epoch 43/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.6667 - loss: 0.6386 - val_accuracy: 0.7500 - val_loss: 0.6354
Epoch 44/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.6667 - loss: 0.6368 - val_accuracy: 0.7500 - val_loss: 0.6351
Epoch 45/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 0.6667 - loss: 0.6366 - val_accuracy: 0.7500 - val_loss: 0.6347
Epoch 46/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 0.6667 - loss: 0.6360 - val_accuracy: 0.7500 - val_loss: 0.6343
Epoch 47/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.6667 - loss: 0.6357 - val_accuracy: 0.7500 - val_loss: 0.6339
Epoch 48/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.6667 - loss: 0.6351 - val_accuracy: 0.7500 - val_loss: 0.6336
Epoch 49/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.6667 - loss: 0.6340 - val_accuracy: 0.7500 - val_loss: 0.6332
Epoch 50/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.6667 - loss: 0.6359 - val_accuracy: 0.7500 - val_loss: 0.6328
Epoch 51/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.6667 - loss: 0.6336 - val_accuracy: 0.7500 - val_loss: 0.6324
Epoch 52/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.6667 - loss: 0.6329 - val_accuracy: 0.7500 - val_loss: 0.6320
Epoch 53/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.6667 - loss: 0.6329 - val_accuracy: 0.7500 - val_loss: 0.6316
Epoch 54/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.6667 - loss: 0.6325 - val_accuracy: 0.7500 - val_loss: 0.6313
Epoch 55/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.6667 - loss: 0.6317 - val_accuracy: 0.7500 - val_loss: 0.6308
Epoch 56/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.6667 - loss: 0.6312 - val_accuracy: 0.7500 - val_loss: 0.6304
Epoch 57/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.6667 - loss: 0.6308 - val_accuracy: 0.7500 - val_loss: 0.6300
Epoch 58/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 0.6667 - loss: 0.6314 - val_accuracy: 0.7500 - val_loss: 0.6296
Epoch 59/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.6667 - loss: 0.6300 - val_accuracy: 0.7500 - val_loss: 0.6292
Epoch 60/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.6667 - loss: 0.6293 - val_accuracy: 0.7500 - val_loss: 0.6288
Epoch 61/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.6667 - loss: 0.6283 - val_accuracy: 0.7500 - val_loss: 0.6284
Epoch 62/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.6667 - loss: 0.6283 - val_accuracy: 0.7500 - val_loss: 0.6280
Epoch 63/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.6667 - loss: 0.6274 - val_accuracy: 0.7500 - val_loss: 0.6276
Epoch 64/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.6667 - loss: 0.6294 - val_accuracy: 0.7500 - val_loss: 0.6272
Epoch 65/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.6667 - loss: 0.6270 - val_accuracy: 0.7500 - val_loss: 0.6268
Epoch 66/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 0.6667 - loss: 0.6260 - val_accuracy: 0.7500 - val_loss: 0.6263
Epoch 67/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.6667 - loss: 0.6265 - val_accuracy: 0.7500 - val_loss: 0.6259
Epoch 68/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 62ms/step - accuracy: 0.6667 - loss: 0.6255 - val_accuracy: 1.0000 - val_loss: 0.6255
Epoch 69/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.6667 - loss: 0.6246 - val_accuracy: 1.0000 - val_loss: 0.6251
Epoch 70/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.6667 - loss: 0.6267 - val_accuracy: 1.0000 - val_loss: 0.6246
Epoch 71/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.6667 - loss: 0.6267 - val_accuracy: 1.0000 - val_loss: 0.6241
Epoch 72/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 0.6667 - loss: 0.6243 - val_accuracy: 1.0000 - val_loss: 0.6238
Epoch 73/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.6667 - loss: 0.6247 - val_accuracy: 1.0000 - val_loss: 0.6233
Epoch 74/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.6667 - loss: 0.6228 - val_accuracy: 1.0000 - val_loss: 0.6229
Epoch 75/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.6667 - loss: 0.6223 - val_accuracy: 1.0000 - val_loss: 0.6224
Epoch 76/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.6667 - loss: 0.6213 - val_accuracy: 1.0000 - val_loss: 0.6219
Epoch 77/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.6667 - loss: 0.6213 - val_accuracy: 1.0000 - val_loss: 0.6215
Epoch 78/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.6667 - loss: 0.6209 - val_accuracy: 1.0000 - val_loss: 0.6211
Epoch 79/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.6667 - loss: 0.6206 - val_accuracy: 1.0000 - val_loss: 0.6207
Epoch 80/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.6667 - loss: 0.6201 - val_accuracy: 1.0000 - val_loss: 0.6202
Epoch 81/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 0.6667 - loss: 0.6198 - val_accuracy: 1.0000 - val_loss: 0.6198
Epoch 82/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.6667 - loss: 0.6185 - val_accuracy: 1.0000 - val_loss: 0.6193
Epoch 83/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 0.6667 - loss: 0.6200 - val_accuracy: 1.0000 - val_loss: 0.6189
Epoch 84/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.6667 - loss: 0.6183 - val_accuracy: 1.0000 - val_loss: 0.6185
Epoch 85/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.6667 - loss: 0.6189 - val_accuracy: 1.0000 - val_loss: 0.6181
Epoch 86/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.6667 - loss: 0.6175 - val_accuracy: 1.0000 - val_loss: 0.6176
Epoch 87/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.6667 - loss: 0.6190 - val_accuracy: 1.0000 - val_loss: 0.6172
Epoch 88/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.6667 - loss: 0.6156 - val_accuracy: 1.0000 - val_loss: 0.6167
Epoch 89/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.6667 - loss: 0.6176 - val_accuracy: 1.0000 - val_loss: 0.6162
Epoch 90/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.6667 - loss: 0.6154 - val_accuracy: 1.0000 - val_loss: 0.6158
Epoch 91/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.6667 - loss: 0.6161 - val_accuracy: 1.0000 - val_loss: 0.6153
Epoch 92/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.6667 - loss: 0.6137 - val_accuracy: 1.0000 - val_loss: 0.6149
Epoch 93/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.6667 - loss: 0.6138 - val_accuracy: 1.0000 - val_loss: 0.6145
Epoch 94/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 0.6667 - loss: 0.6135 - val_accuracy: 1.0000 - val_loss: 0.6140
Epoch 95/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.6667 - loss: 0.6123 - val_accuracy: 1.0000 - val_loss: 0.6135
Epoch 96/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.6667 - loss: 0.6137 - val_accuracy: 1.0000 - val_loss: 0.6131
Epoch 97/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 0.6667 - loss: 0.6126 - val_accuracy: 1.0000 - val_loss: 0.6127
Epoch 98/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.6667 - loss: 0.6119 - val_accuracy: 1.0000 - val_loss: 0.6122
Epoch 99/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 0.6667 - loss: 0.6109 - val_accuracy: 1.0000 - val_loss: 0.6117
Epoch 100/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 0.6667 - loss: 0.6107 - val_accuracy: 1.0000 - val_loss: 0.6112